### ISSUE TITLE
Only processes 64k-ish of long sequences??

### ISSUE THREAD

**Issue by kushtun** [freezer333/qgrs-cpp#1]
Was trying this out, and on some shorter sequences, all good.  But when I try any longer (>100k) sequences, it stops reporting any hits at about what looks like 64k in.

Bug, or... ???

Thanks for any assistance you can provide.

Tom

**Comment by freezer333** [comment]
Is it for any 100K+ sequence, or do you have a specific test case?

**Comment by kushtun** [comment]
I have run several - a couple of examples:NC_001666.2 Zea mays chloroplast  (https://www.ncbi.nlm.nih.gov/nuccore/11994090?report=fasta)
KM103369.1   Oryza sativa cultivar TN1 chloroplast (https://www.ncbi.nlm.nih.gov/nuccore/743432831?report=fasta)

both are ~140k bp

running as :
1) qgrs -i zm_chloro_NC_001666.2.fa -o zm_chloro.out

last hits are:
...
76          63112  63121  63129  63135  2  19  CCATTTTATGGGCGAAAGGCGGGGG
77          64493  64501  64509  64521  2  18  TTTAATTTGGAATAGCGGCCAAGATCTTGG
78          64932  64937  64940  64946  2  19  CCCTCGGGGGTCGTGG

 
2) qgrs -i oryza_chloroplast_KM103369.1.fa -o oryza_chloro.out
last hits are:
...
110         64640  64642  64646  64649  2  19  AAGGAAGGAGG
111         65221  65229  65236  65243  2  20  GGAAAGGAGGTTCATGGCCAAGGG
112         65299  65308  65314  65319  2  18  GGCCAATGAGGAGTCGGCAGGG

From other G4 tools, there are certainly hits through toward the 3' end.

Additionally, if I try to run with larger sequences (e.g. Zea mays mitochondrials (NA/NB/CMS-S/... => 500k nt to 700k nt) it takes so much memory the process is killed.
It would be good to be able to operate on chromosomal size pieces, but it seems that isn't currently possible.

Regards,
Tom

**Comment by freezer333** [comment]
Hi Tom - OK, understood.  I will let you know as soon as I get a chance to update the code - it sounds like it's running out of memory for longer sequences, I'll need to reorganize some of the code to handle those situations better.

**Comment by freezer333** [comment]
Hi Tom - very sorry it took so long for me to get back to this.  I make a small adjustment to the code and it can handle over 64K sequences now.  The larger mitochondrials you mentioned still consume too much memory though.  The algorithm we use deals with overlapping G4 differently than others, and it does end up being pretty memory intensive.  Hopefully I can get some time soon to redesign parts of it to allow for these larger sequences to be run.
