### ISSUE TITLE
Bioconda recipe for qgrs-cpp

### ISSUE THREAD

**Issue by npavlovikj** [freezer333/qgrs-cpp#3]
Hi,

I am contributor to "bioconda", https://bioconda.github.io/, and I would like to create a conda package for "qgrs-cpp". However, one of the requirements for this, is to have a tagged release. Therefore, can you please tag a release and create a tarball for it so I can proceed?

Thank you in advance, and please let me know if you have any questions regarding this request.

Thank you,
Natasha

**Comment by freezer333** [comment]
Sure - thanks for doing this!  Just added a tagged release.

**Comment by npavlovikj** [comment]
Hi @freezer333 ,

Many thanks for the prompt reply!

I added `qgrs-cpp` to the bioconda channel, https://anaconda.org/bioconda/qgrs-cpp.
Assuming the user has conda installed, they can now install and use `qgrs` as:
```
conda create -n qgrs-cpp-1.0 -c conda-forge -c bioconda -c defaults qgrs-cpp
conda activate qgrs-cpp-1.0
qgrs <options>
conda deactivate
```

`qgrs-cpp` is available for Linux and MacOS, and you can check the recipe here, https://github.com/bioconda/bioconda-recipes/tree/6a45e30dca0884b69c6832b2d64049f521858b12/recipes/qgrs-cpp.

I tested the conda package with the provided examples, and everything worked fine.
If you have any issues with it, please let me know.

Thank you,
Natasha

**Comment by freezer333** [comment]
Thank you!
